import React from "react";
import Head from "next/head";

function Benefits() {
  return (
    
    <>
      <Head>  <title>Milosevic/Dental</title>
        <meta property="og:title" content="Beli zubi." />
        <meta property="og:description" content="Mi učestvujemo u stvaranju zdravih, lepih osmeha koji menjaju život u potpunosti.Smatramo da zaslužujete najbolju stomatološku negu. " />
        <meta property="og:image" content="https://weblala.online/whiteTheeth.jpg" />   
        <meta name="google" content="notranslate" />
  </Head>
      <div className="global-global">
        <div
          className="globalpage-container"
          style={{
            backgroundImage:
              "linear-gradient(180deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)),url('/whiteTheeth.jpg')",
          }}
        >
          <div className="globalpage-text">
            <h1>NAJVEĆE PREDNOSTI BELIH ZUBA</h1>
          </div>
        </div>
        <div className="global-img"></div>
      </div>
      <div className="globalcontent-container">
        <p>
          ZA SVE VIŠE LJUDI IZBJELJIVANJE ZUBA POSTALO JE POTREBA, POTREBA KOJA
          IM POMAŽE DA IZGLEDAJU I DA SE OSEĆAJU BOLJE. KUDA GOD POGLEDATE, OD
          SLIKA IZ ČASOPISA DO VAŠEG INSTAGRAMA, PRIMEĆUJETE VELIKU VAŽNOST
          DA IMATE ČISTE, BELE ZUBE.
          <br></br> ALI MOŽDA NISTE SIGURNI ZAŠTO JE IZBELJIVANJE ZUBA TAKO
          VELIKA POTREBA I DA LI UOPŠTE ZAISTA VAŽNO. SIGURNO NEŠTO TAKO
          JEDNOSTAVNO NE MOŽE IMATI TOLIKI UTICAJ NA VAŠ OPŠTI ŽIVOT?<br></br>
          STVARNOST JE DA IZBJELJIVANJE ZUBA MOŽE BITI ZNAČAJAN TRETMAN KOJI
          UNAPREĐUJE ŽIVOT. AKO SE JOŠ UVEK DVOUMITE, NASTAVITE DA ČITATE I
          NAUČITE SVE O NAJVEĆIM PREDNOSTIMA BELIH ZUBA.
        </p>
        <h3>BUDITE PRIVLAČNIJI</h3>
        <p>
          IMATI ZDRAVU KOŽU I RAVNE ZUBE JE NEVEROVATNO VAŽNO, ALI I AKO TO VEĆ
          IMATE, SVE JE ZA DZABE AKO SU VAŠI ZUBI ŽUTI. TO MOŽE DA SE DESI
          SVIMA, ZAHVALJUJUĆI TAMNIM TEČNOSTIMA POPUT KAFE, ČAJEVA I GAZIRANIH
          SOKOVA. MOGUĆE JE „POPRAVITI“ IZGLED ZUBA NA FOTOGRAFIJAMA PRAVIM
          FILTEROM, ALI ZAŠTO DA NE IDETE DO POTPUNOG ISKUSTVA IZBELJIVANJA
          ZUBA?
        </p>
        <h3>POVEĆAJTE VAŠE SAMOPOUZDANJE</h3>
        <p>
          KAO ŠTO SVAKI Šminker ILI PLASTIČNI HIRURG MOŽE DA VAM KAŽE, KADA
          IZGLEDATE NEVEROVATNO, OSEĆATE SE NEVEROVATNO, A TO REZULTIRA VEĆIM
          SAMOPOUZDANJEM. ČAK I AKO TRENUTNO NISTE NAROČITO SVESNI IZGLEDA
          SVOJIH ZUBA, RAZMISLITE KAKO BI BIO DOBAR OSEĆAJ DA NA VAŠEM SLEDEĆEM
          SASTANKU ZABLISTATE SVOJIM SAVRŠENIM Osmehom. ILI, KAKO BISTE SE
          OSEĆALI KAD BISTE DRŽALI PREZENTACIJU NA POSLU, ZNAJUĆI DA SU VAŠI
          ZUBI U ISTANČANOM, SAVRŠENOM STANJU.
        </p>
        <h3>USPEH NA POSLU</h3>
        <p>
          PREMA ISTRAŽIVANJU 74% ODRASLIH MISLI DA NEATRAKTIVAN OSMEH MOŽE
          POVREDITI NJIHOV PROFESIONALNI ŽIVOT. I NISU POGREŠNI: OD VAŠEG
          DIREKTNOG IZGLEDA DO NIVOA SAMOPOUZDANJA, STANJE VAŠIH ZUBA MOŽE MNOGO
          UTICATI NA VAŠ PROFESIONALNI USPEH. AKO IMATE INTERVJU, BELJI OSMEH
          MOŽE VAM POMOĆI DA OSTAVITE BOLJI PRVI UTISAK ZAHVALJUJUĆI SVOM ČISTOM
          IZGLEDU. VEĆ SMO GOVORILI KAKO ZUBI BOLJEG IZGLEDA POBOLJŠAVAJU
          SAMOPOUZDANJE. A PORED TOGA, OSEĆAĆETE SE KOMFORNIJE — I PONOSNIJE —
          POKAZUJUĆI SVOJ Osmeh, ŠTO GOVORI SAGOVORNIKU DA STE SIGURNI U SVOJU
          SPOSOBNOST DA OBAVLJATE POSAO.
        </p>
        <h3>BELJENJE ZUBA JE PRISTUPAČAN TRETMAN</h3>
        <p>
          BUDIMO ISKRENI: IZBJELJIVANJE ZUBA JE INVESTICIJA, ALI JE JEFTINA U
          poređenju sa stvarima poput PLASTIČNE HIRURGE. ČAK I U poreDJenju sa
          DRUGIM STOMATOLOŠKIM PROCEDURAMA, USLUGE IZBELJIVANJA ZUBA NE KOŠTAJU
          TOLIKO. A AKO VAM JE GNJAVAŽA DA ZAKAŽETE KOD STOMATOLOGA, RAZMISLITE:
          TO JE ULAGANJE U TO KAKO SE PREDSTAVLJATE SVETU, I NA MNOGE NAČINE
          ULAGANJE U VAŠU BUDUĆNOST. ZAR NE MISLITE DA VAŠ OSMEH ZASLUŽUJE MALO
          LJUBAVI?
        </p>
        <h3>PRIJA VAŠIM ZUBIMA</h3>
        <p>
          ČESTA ZABLUDA OKO TRETMANA IZBELJIVANJA ZUBA JE DA OŠTEĆUJU VAŠE ZUBE,
          DA OŠTEĆUJU GLEDJ I POVEĆAVAJU OSETLJIVOST ZUBA. IAKO ODREĐENI KUĆNI
          TRETMANI MOGU DA IZAZOVU BOL ILI BLAŽA OŠTEĆENJA NEKIM LJUDIMA, AKO SE
          OBRATITE KVALIFIKOVANOM STOMATOLOGU ZA LEČENJE, APSOLUTNO NEMATE O
          ČEMU DA BRINETE. <br></br>
          MRLJE NA VAŠIM ZUBAMA SE TALOŽE NA POVRŠINI, UZROKOVANE HRANOM KOJU
          JEDETE. BAŠ KAO ŠTO VAŠA HRANA NIJE TRAJNO OŠTETILA ZUBE, NEMA LOGIKE
          DA BI UKLANJANJE MRLJA REZULTIRALO BILO KAKVOM ŠTETOM. BELJENJE ZUBA
          SAMO UKLANJA EFEKTE MRLJA. KAO KOZMETIČKO POBOLJŠANJE, SAVRŠENO JE
          BEZBEDNO..<br></br>
          UOPŠTE, IZBJELJIVANJE ZUBA DAJE VIŠE RAZLOGA ZA SMIJEH. A OSMIJEH
          MOŽE DA UČINI DA SE OSEĆATE BOLJE, ŠTO PONOVNO POTVRĐUJU STRUČNJACI
          PSIHOLOGIJE. NE SAMO DA JE IZBJELJIVANJE ZUBA SAVRŠENO BEZBEDNO I
          PRILIČNO PRISTUPAČNO, VEĆ SA SOBOM NOSI MNOGE PREDNOSTI I MOGUĆNOSTI.
        </p>
      </div>
    </>
  );
}

export default Benefits;
