import React from "react";

function Habits() {
  return (
    <>
      <div className="global-global">
        <div
          className="globalpage-container"
          style={{
            backgroundImage:
              "linear-gradient(180deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)),url('/habits.jpg')",
          }}
        >
          <div className="globalpage-text">
            <h1>PET SVAKODNEVNIH NAVIKA KOJE OŠTEĆUJU VAŠE ZUBE</h1>
          </div>
        </div>
        <div className="global-img"></div>
      </div>
      <div className="globalcontent-container">
        <p>
          NAŠI ZUBI IGRAJU OSNOVNU ULOGU U NAŠIM ŽIVOTIMA. ONI NAM POMAŽU DA
          ŽVAĆEMO I SVARIMO NAŠU HRANU I JASNO RAZGOVARAMO.ONI TAKODJE DOPRINOSE
          NAŠEM IZGLEDU. ZDRAVA USTA POMAŽU U PREVENCIJI MEDICINSKIH STANJA KAO
          ŠTO SU BOLESTI SRCA I DIJABETES. MEĐUTIM, SKORO 20% ODRASLIH STARIJIH
          OD 65 JE IZGUBILO SVE ZUBE, PREMA CENTRU ZA KONTROLU BOLESTI.{" "}
          <br></br> EVO PET SVAKODNEVNIH NAVIKA KOJE, PREMA STOMATOLOZIMA,
          OŠTEĆUJU ZUBE:
        </p>
        <h1>ISPIJANJE GAZIRANIH ILI ZASLADJENIH PIĆA</h1>
        <p>
          ISPIJANJE GAZIRANIH PIĆA, ČAK I ONIH BEZ ŠEĆERA, MOŽE DOVESTI DO
          OŠTEĆENJA ZUBA. BEZALKOHOLNA PIĆA SADRŽE KISELINE, KOJE MOGU OMEKŠATI
          ZUBNU GLEDJ I DOVESTI DO GUBITKA GLEDJI I DO POJAVE KARIJESA. ČAK SAMO
          JEDNO GASIRANO PIĆE DNEVNO MOŽE ZNAČAJNO OŠTETITI ZUBE. SOKOVI
          ZASLAĐENI ŠEĆEROM TAKOĐE MOGU NEGATIVNO DA UTIČU NA ORALNO ZDRAVLJE.
          RAZMOTRITE DA ZAMENITE GAYIRANA PIĆA I ZASLAĐENE SOKOVE VODOM. AKO
          POVREMENO UZMETE bezalkoholno piće, POSLE ISPIRAJTE USTA VODOM DA
          BISTE SMANJILI RIZIK DA KISELINA I ŠEĆER OŠTETE ZUBE.<br></br>{" "}
          ALKOHOLNA PIĆA TAKODJE NISU DOBRA ZA ZUBE. NE POSTOJE IZUZECI, ČAK I
          VINO JE ISTO TOLIKO ŠTETNO ZA ZUBE KAO I BILO KOJE DRUGO ALKOHOLNO
          PIĆE. TAKOĐE, ALKOHOLNA PIĆA ISUŠUJU USTA, SMANJUJUĆI PROIZVODNJU
          PLJUVAČKE. PLJUVAČKA JE ESENCIJALNA ZA ZDRAVLJE ZUBA. AKO PIJETE
          ALKOHOL, OBAVEZNO POSLE ISPERITE USTA VODOM.
        </p>
        <h1>GRICKANJE NOKTIJU</h1>
        <p>
          GRICKANJE NOKTIJU MOŽE PROUZROKOVATI OŠTEĆENJA ZUBA I DESNI. GRICKANJE
          NOKTIJU ZAHTEVA PRITISAK, A TAJ PRITISAK MOŽE RASKLATITI I OŠTETITI
          ZUBE. VAŠE RUKE OBIČNO SADRŽE MNOGO BAKTERIJA I PATOGENA. PATOGENI
          MOGU DA DOVEDU DO INFEKCIJE DESNIH,DO RAZNIH BOLESTI I DRUGIH FIZIČKIH
          POTEŠKOĆA.
          <br></br>
          ŽVAKANJE NOKTIJU VRŠI VILICA. VAŠA VILICA MORA DA ODRŽI PRITISAK
          PRITISAK, DUŽE ODRŽAVANJE PRITISKA MOŽE DA DOVEDE DO DISFUNKCIJE
          VILICE.
          <br></br>
          DA BISTE PREKINULI NAVIKU ŽVAĆANJA NOKTE, RAZMOTRITE NANOŠENJE NEŠTO
          GORKOG UKUSA NA NOKTE. DRUGA OPCIJA JE VEŽBAVANJE TEHNIKA SMANJENJA
          STRESA. KONAČNO, VODITE BEČEŠKE DA BISTE UTVRDILI KOJE SITUACIJE
          POKREĆU GRICKANJE NOKTIJU.BUDITE U PRIPREMI SA ALTERNATIVNIM OPCIJAMA
          KAKO BI SPREČILI SEBE DA GRICKATE NOKTE KADA DODJE DO TAKVIH
          SITUACIJA.
        </p>
        <h1>ŽVAKANJE OLOVAKA I HEMIJSKI</h1>
        <p>
          ČESTA NAVIKA JE ŽVAKANJE OLOVKE ILI HEMIJSKE. ČESTO DECA ILI ODRASLI
          USVAJAJU OVU NAVIKU KADA IMAJU STANJE KOJE SE ZOVE "HIPEROSETLJIVOST"
          USTA. MNOGI LJUDI UOPŠTE NISU TOGA SVESNI. MEĐUTIM, AKO SE OVAKVO
          PONAŠSANJE NASTAVLJA DUŽE VREME, ONO MOŽE DA DOVEDE DO OZBILJNOG
          OŠTEĆENJA ZUBA.
          <br></br>
          ONI KOJI ŽVAĆU OLOVKE SU U POVEĆANOM RIZIKU OD STRESOVNIH PRELOMA
          ZUBA, NAPRSNUĆA ZUBA I OŠTEĆENJA NA ZUBAMA. OVA NAPRSNUĆA I OŠTEĆENJA
          MOGU NA KRAJU DA DOVEDU DO KARIJESA I, U NEKIM SLUČAJEVIMA, GUBITKA
          ZUBA. AKO POSTOJE STOMATOLOŠKI RADOVI NA ZUBIMA KAO ŠTO SU PLOMBE,
          IMPLANTI ILI KRUNICE, OŠTEĆENJA MOGU DA BUDU I GORA.
          <br></br>
          NA SREĆU, NAVIKA ŽVAKANJA OLOVAKA I HEMIJSKI MOĆE BITI ZAMENJENA
          ŽVAKANJEM NEČEG MANJE ŠTETNOG ZA ZUBE KAKO ŠTO JE ŽVAKA BEZ ŠEĆERA.
          ČAK I TERAPIJA ILI HIPNOZA SU MOGUĆNOSTI U EKSTREMNIM SLUČAJEVIMA.
        </p>
        <h1>UPOTREBA ZUBA KAO ALATA</h1>
        <p>
          JEDAN OD NAJSIGURNIJIH NAČINA DA OŠTETite ZUBE JE DA IH KORISTITE KAO
          OTVARAČ,KLJEŠTA ILI MAKAZE. ZUBI NE SLUŽE KAO ZAMENA ZA ALAT.
          KORIŠĆENJEM ZUBA KAO ALATA MOŽE VAS IZLOŽITI RIZIKU OD OŠTEĆENJA
          GLEDJI ILI KORENA ZUBA, PUCANJU ZUBA, POVREDI VILICE ILI SLUČAJNOG
          GUTANJA NEČEG OPASNOG. ČAK I AKO ODMAH NE PREPOZNATE OŠTEĆENJE ZUBA,
          MOŽETE DA NAPRAVITE MALU NAPUKLINU NA ZUBU I TAKO GA DODATNO OSLABITE.
          KAKO VREME PROLAZI jaz se MOŽE PROŠIRITI ILI ZUB I DALJE OSLABITI, ŠTO
          VODI DO POTPUNOG GUBITKA ZUBA ILI OŠTEĆENJA DESNI.<br></br>
          DRŽITE ALAT, KAO ŠTO su DZEPNI OTVARAČI ZA FLAŠICE I MAKAZE, PRI RUCI.
          AKO ALATI NISU U BLIZINI, ZASTANITE I PRONAĐITE IH,BOLJE NEGO DA
          KORISTITE ZUBE. AKO SU VAŠE RUKE PUNE, ODUPRITE SE NAGONU DA NOSITE
          DODATNE PREDMETE U ZUBIMA. PRONAĐITE POSUDU, KUTIJU ILI TORBU ZA
          NOŠENJE DODATNIH PREDMETA ILI ZAMOLITE PRIJATELJA DA VAM POMOGNE.
          <br></br>
          PROMENA OVE NAVIKE MOŽE BITI TEŠKA I POTREBNO JE VREME DA SE POBEDI.
          POKUŠAJTE DA PREDUZMETE MALE KORAKE DOK NEZDRAVE NAVIKE ZAMENJUJETE
          ZDRAVIMA. BUDITE NEŽNI PREMA SEBI. ZAPAMTITE, POBEDA OVIH LOŠIH NAVIKA
          JE VREDNA ZA VAŠE DUGOTRAJNO ORALNO ZDRAVLJE I ODRŽAVANJE LEPOG
          OSMEHA.
        </p>
        <h1>ŽVAKANJE LEDA</h1>
        <p>
          MNOGI LJUDI ŽVAĆU LED NAKON ISPIJANJA PIĆA. LED JE SAMO ZAMRZNUTA
          VODA, TAKO JE ŽVAKANJE MOŽDA NAIZGLED BEZAZLENA NAVIKA. MEĐUTIM, TO
          MOŽE REZULTIRATI GUBITKOM ZUBNE GLEDJI ILI POVREDOM PLOBE. NAPRSNUĆA
          ZUBNE GLEDJI MOGU DA POSTANU TEŽA SA STARANJEM, DA NEGATIVNO UTIČU NA
          ZDRAVLJE USTA. AKO JE ZUB VEĆ ISTROŠEN ILI OŠTEĆEN, LED MOŽE DOVESTI
          DO NAPRSNUĆA I OŠTETITI ZUBNU STRUKTURU. LED TAKOĐE MOŽE OŠTETI
          PROTEZE ILI plombe I IRITIRATI VAŠE DESNI.<br></br>
          DA BISTE IZBEGLI ISKUŠENJE DA ŽVAĆETE LED, RAZMOTRITE DA NARUČITE
          NAPITAK BEZ LEDA ILI DA GA PIJETE SAMO PREKO SLAMKE.<br></br>
          AKO VAM JE POSEBNO TEŠKO PREKINUTI NAVIKU ŽVAKANJA LEDA, MOŽDA IMATE
          MEDICINSKO STANJE POZNATO KAO PAGOFAGIJA. PAGOFAGIJA SE LEČI. LEČENJE
          ZAVISI OD OSNOVNOG UZROKA VAŠE PAGOFAGIJE. LEKAR MOŽE POMOĆI DA SE
          UTVRDI UZROK I NAJBOLJA OPCIJA LEČENJA.
        </p>
        <p>
        AKO IMATE OŠTEĆENih ZUBA ILI ŽELITE DA RAZGOVARATE SA STOMATOLOGOM O PREKIDU
        nekih od OVih NAVIKa, KONTAKTIRAJTE MILOŠEVIĆ/DENTAL NA <a href="tel:00381652828678">+381/65-28-28-678</a>.
        </p>
      </div>
    </>
  );
}

export default Habits;
