import React from 'react'

function TeamHead() {
  return (
    <div className='teamhead-container'>
    <div className='teamhead-img'></div>
  <div className='teamhead-text'>
    <div className='teamhead-title'>
    <h6 >DR.MILICA MILOŠEVIĆ</h6>
    </div >
    <p>VERUJEMO DA ZASLUŽUJTE NAJBOLJU STOMATOLOŠKU NEGU. ZATO NUDIMO ŠIROK SPEKTAR KOZMETIČKIH REŠENJA, PORODIČNE NEGE I TRETMANA SKROJENIH PO MERI KOJI NAJBOLJE ODGOVARAJU VAMA I VAŠOJ PORODICI. MI UCESTVUJEMO U STVARANJU ZDRAVIH, LEPIH OSMEHA KOJI MENJAJU ŽIVOT U POTPUNOSTI. <br /> <br />
    SHE HAS A PASSION FOR THE AESTHETIC SIDE OF DENTISTRY, AND HAS TRAVELED THE WORLD LEARNING ABOUT THE MOST UP-TO-DATE TECHNOLOGIES AND TECHNIQUES TO DELIVER WORLD CLASS DENTISTRY TO HER PATIENTS BACK HOME IN KNOXVILLE. SHE UNDERSTANDS THE VALUE AND IMPORTANCE OF CONTINUED EDUCATION, AND TAKES AT LEAST 100 HOURS OF CONTINUED EDUCATION PER YEAR, 5 TIMES THE AMOUNT REQUIRED BY THE STATE OF TENNESSEE.
    </p>
  </div>
</div>
  )
}

export default TeamHead